on: [push, pull_request]
name: Test on macOS
jobs:
  test:
    strategy:
      matrix:
        python-version: [2.7, 3.9]
        os: [macos-11, macos-12, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install ImageMagick
        run: brew install imagemagick
      - name: make test
        run: make test
